"""
Comprehensive Analysis of CPR Prediction Failures
Root Cause Analysis and Alternative Model Development
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.stats import pearsonr
import warnings
warnings.filterwarnings('ignore')

# --- EMBEDDED DATASET: ALL 312 EXPERIMENTS ---
embedded_data_full_list = [
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.9668, 'Exploration': 0.432},
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0024, 'Exploration': 0.005},
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0111, 'Exploration': 0.0097},
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0122, 'Exploration': 0.0103},
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.183, 'Exploration': 0.112},
    {'Config': '6,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0629, 'Exploration': 0.0333},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0077, 'Exploration': 0.0073},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0059, 'Exploration': 0.0057},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0, 'Exploration': 0.003},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0, 'Exploration': 0.0133},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0321, 'Exploration': 0.022},
    {'Config': '6,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.016, 'Exploration': 0.0107},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.5462, 'Exploration': 0.2457},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0022, 'Exploration': 0.0023},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.024, 'Exploration': 0.0137},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0184, 'Exploration': 0.012},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0095, 'Exploration': 0.0093},
    {'Config': '6,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0022, 'Exploration': 0.0023},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0055, 'Exploration': 0.0057},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0042, 'Exploration': 0.0043},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0, 'Exploration': 0.0033},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0, 'Exploration': 0.0037},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.1e-05, 'Complexity': 0.0022, 'Exploration': 0.0023},
    {'Config': '6,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.1e-05, 'Complexity': 0.0042, 'Exploration': 0.0043},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 2.3458, 'Exploration': 0.9613},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0955, 'Exploration': 0.054},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 0.0211, 'Exploration': 0.0137},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0312, 'Exploration': 0.019},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 2.2568, 'Exploration': 0.928},
    {'Config': '8,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0431, 'Exploration': 0.0277},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 0.0121, 'Exploration': 0.011},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0139, 'Exploration': 0.0127},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 0.0, 'Exploration': 0.0037},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0, 'Exploration': 0.005},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 1.1935, 'Exploration': 0.511},
    {'Config': '8,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.087, 'Exploration': 0.0477},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 2.4355, 'Exploration': 0.9957},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0293, 'Exploration': 0.017},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 0.3554, 'Exploration': 0.165},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0443, 'Exploration': 0.0243},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 1.444, 'Exploration': 0.624},
    {'Config': '8,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0142, 'Exploration': 0.0093},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 2.4269, 'Exploration': 0.9923},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0404, 'Exploration': 0.0233},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 0.0, 'Exploration': 0.0047},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.0, 'Exploration': 0.0043},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.39e-06, 'Complexity': 2.0216, 'Exploration': 0.837},
    {'Config': '8,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.39e-06, 'Complexity': 0.021, 'Exploration': 0.0137},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.7559, 'Exploration': 0.3583},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0658, 'Exploration': 0.0367},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.1179, 'Exploration': 0.0653},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0117, 'Exploration': 0.008},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0103, 'Exploration': 0.007},
    {'Config': '6,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0091, 'Exploration': 0.0067},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0073, 'Exploration': 0.008},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0072, 'Exploration': 0.008},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0, 'Exploration': 0.0087},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0, 'Exploration': 0.013},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.4023, 'Exploration': 0.1863},
    {'Config': '6,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.1182, 'Exploration': 0.06},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0981, 'Exploration': 0.054},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0361, 'Exploration': 0.0203},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.1651, 'Exploration': 0.08},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.2229, 'Exploration': 0.1093},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0147, 'Exploration': 0.0107},
    {'Config': '6,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0073, 'Exploration': 0.0053},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.5008, 'Exploration': 0.2463},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0355, 'Exploration': 0.02},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0, 'Exploration': 0.005},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0, 'Exploration': 0.005},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.39e-06, 'Complexity': 0.0469, 'Exploration': 0.032},
    {'Config': '6,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.39e-06, 'Complexity': 0.0073, 'Exploration': 0.0053},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.7349, 'Exploration': 0.3283},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.2588, 'Exploration': 0.1347},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.4828, 'Exploration': 0.2407},
    {'Config': '8,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.2782, 'Exploration': 0.1453},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.0118, 'Exploration': 0.0107},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0118, 'Exploration': 0.0107},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.0, 'Exploration': 0.01},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0008, 'Exploration': 0.0173},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 2.3204, 'Exploration': 0.9513},
    {'Config': '8,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.2727, 'Exploration': 0.132},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 2.3253, 'Exploration': 0.9537},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.078, 'Exploration': 0.0403},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.4719, 'Exploration': 0.2193},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0234, 'Exploration': 0.014},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.8466, 'Exploration': 0.3923},
    {'Config': '8,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0051, 'Exploration': 0.004},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 1.5658, 'Exploration': 0.6697},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 0.0, 'Exploration': 0.006},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0, 'Exploration': 0.006},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.73e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '8,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.73e-08, 'Complexity': 0.0439, 'Exploration': 0.0247},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 0.0789, 'Exploration': 0.0517},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.0339, 'Exploration': 0.023},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.6997, 'Exploration': 0.3173},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 0.0064, 'Exploration': 0.007},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.006, 'Exploration': 0.0067},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 0.0, 'Exploration': 0.005},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.0, 'Exploration': 0.0043},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.3882, 'Exploration': 0.9773},
    {'Config': '10,7', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.1934, 'Exploration': 0.1},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.5729, 'Exploration': 0.257},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 0.2633, 'Exploration': 0.1237},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.1073, 'Exploration': 0.0543},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.0567, 'Exploration': 0.0307},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 0.0, 'Exploration': 0.004},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.0, 'Exploration': 0.0053},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.54e-08, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,7', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.54e-08, 'Complexity': 0.1781, 'Exploration': 0.086},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 0.0438, 'Exploration': 0.0263},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.6793, 'Exploration': 0.3163},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 0.0219, 'Exploration': 0.016},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.0153, 'Exploration': 0.0113},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 0.0, 'Exploration': 0.0073},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.0, 'Exploration': 0.0057},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 1.542, 'Exploration': 0.6607},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.078, 'Exploration': 0.0403},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 0.4479, 'Exploration': 0.2087},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.217, 'Exploration': 0.1027},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 1.4682, 'Exploration': 0.6247},
    {'Config': '12,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.0361, 'Exploration': 0.0203},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 2.2738, 'Exploration': 0.9343},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.2053, 'Exploration': 0.1033},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 0.0, 'Exploration': 0.006},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.0, 'Exploration': 0.0067},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.82e-12, 'Complexity': 1.4415, 'Exploration': 0.6193},
    {'Config': '12,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.82e-12, 'Complexity': 0.0567, 'Exploration': 0.0317},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 0.7913, 'Exploration': 0.3497},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.1694, 'Exploration': 0.0883},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 1.414, 'Exploration': 0.6013},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 0.1047, 'Exploration': 0.0587},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.099, 'Exploration': 0.0557},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 0.0002, 'Exploration': 0.0137},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.0, 'Exploration': 0.007},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 0.3643, 'Exploration': 0.169},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.1668, 'Exploration': 0.0807},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.3031, 'Exploration': 0.14},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 0.0004, 'Exploration': 0.0137},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.0, 'Exploration': 0.0073},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 7.25e-11, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '10,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 7.25e-11, 'Complexity': 0.3247, 'Exploration': 0.1497},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.2684, 'Exploration': 0.145},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.1381, 'Exploration': 0.0797},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.7636, 'Exploration': 0.3403},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.7364, 'Exploration': 0.3333},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.0017, 'Exploration': 0.021},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.0, 'Exploration': 0.008},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.624, 'Exploration': 0.284},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.0055, 'Exploration': 0.0043},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.634, 'Exploration': 0.28},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.2998, 'Exploration': 0.141},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.9597, 'Exploration': 0.4157},
    {'Config': '12,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.0055, 'Exploration': 0.0043},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 1.5578, 'Exploration': 0.6633},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.02, 'Exploration': 0.0153},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 0.0, 'Exploration': 0.0057},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.0269, 'Exploration': 0.063},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 5.15e-13, 'Complexity': 1.2159, 'Exploration': 0.53},
    {'Config': '12,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 5.15e-13, 'Complexity': 0.0081, 'Exploration': 0.0063},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 1.0623, 'Exploration': 0.4633},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 0.2611, 'Exploration': 0.134},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 1.9404, 'Exploration': 0.8043},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 1.685, 'Exploration': 0.7083},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 0.0, 'Exploration': 0.0083},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 0.0, 'Exploration': 0.01},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 0.111, 'Exploration': 0.057},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 0.3062, 'Exploration': 0.1417},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 0.137, 'Exploration': 0.0673},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 1.1556, 'Exploration': 0.5113},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 0.0, 'Exploration': 0.0083},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 0.0092, 'Exploration': 0.038},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '15,11', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 3.59e-15, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 0.7975, 'Exploration': 0.366},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.0963, 'Exploration': 0.868},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 0.0, 'Exploration': 0.0103},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 0.0, 'Exploration': 0.0107},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.3674, 'Exploration': 0.969},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 0.917, 'Exploration': 0.3967},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 0.0, 'Exploration': 0.0103},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 0.0, 'Exploration': 0.0093},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '20,13', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.05e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 1.5281, 'Exploration': 0.642},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.5126, 'Exploration': 0.2487},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 0.001, 'Exploration': 0.017},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.0003, 'Exploration': 0.0113},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.2023, 'Exploration': 0.0963},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 0.857, 'Exploration': 0.374},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.776, 'Exploration': 0.3373},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.0952, 'Exploration': 0.0483},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.3464, 'Exploration': 0.162},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 0.0015, 'Exploration': 0.0177},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.0001, 'Exploration': 0.0093},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 1.28e-21, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '18,17', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 1.28e-21, 'Complexity': 0.2815, 'Exploration': 0.138},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4388, 'Exploration': 0.997},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 0.0005, 'Exploration': 0.0133},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 0.0006, 'Exploration': 0.0137},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.1407, 'Exploration': 0.8823},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 0.0003, 'Exploration': 0.0107},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 0.0469, 'Exploration': 0.0823},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '25,19', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 2.69e-31, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'adjacent_duplicates', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 0.0031, 'Exploration': 0.0227},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 0.0244, 'Exploration': 0.0607},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'sum_limits', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4172, 'Exploration': 0.9883},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 0.293, 'Exploration': 0.1417},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'pattern_prohibition', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'additive', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 0.001, 'Exploration': 0.0147},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'multiplicative', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 0.0233, 'Exploration': 0.0573},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'uniform_distribution', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0},
    {'Config': '30,23', 'Constraint': 'local_entropy', 'Mixing': 'triple_sum', 'Governor': 'entropy_maximization', 'CPR': 4.22e-40, 'Complexity': 2.4467, 'Exploration': 1.0}
]

# Model parameters from current framework
L_GLOBAL = 0.8513
K_GLOBAL = 46.7978
X0_GLOBAL = -8.2999

def sigmoid_model(log_cpr, L, k, x0):
    """Standard sigmoid model"""
    return L / (1 + np.exp(-k * (log_cpr - x0)))

# Create DataFrame
df = pd.DataFrame(embedded_data_full_list)
df['log_CPR'] = np.log10(df['CPR'])
df['Architecture'] = df['Constraint'] + '_' + df['Mixing'] + '_' + df['Governor']

# Normalize constraint names
df['Constraint'] = df['Constraint'].replace('adjacent_duplicates', 'pattern_prohibition')
df['Constraint'] = df['Constraint'].replace('sum_limits', 'sum_modulation')

print("="*80)
print("CPR PREDICTION FAILURE ANALYSIS")
print("="*80)
print(f"\nTotal experiments: {len(df)}")
print(f"Unique architectures: {df['Architecture'].nunique()}")
print(f"CPR range: {df['CPR'].min():.2e} to {df['CPR'].max():.2e}")
print(f"Exploration range: {df['Exploration'].min():.4f} to {df['Exploration'].max():.4f}")
